### ISSUE TITLE
Admin can provide key ID

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-nethsm#6]
The hash should be base64url encoded.

SHA1 or SHA256 (or even half a SHA256) are possible candidates. The risks of collisions should be considered too. Ideally during key generation/import the device checks for collisions and applies a work around.

To get an impression how long those hashes are, here are examples:
SHA1: rr1MLoGs6S69oryQmso0oTn/LOo=
SHA256: LzIAkwJM9YatJW2K5BvvH+LAO3nzhU0+RQDZ524FLAk=

**Comment by ansiwen** [comment]
Or the id is provided by the user, so she can decide, if the IDs should be hashes or random or speaking identifiers.
